src/Web/Areas/Admin/Models/API/Emulator/SensorEmulatorListItemModel.cs
namespace Web.Areas.Admin.Models.API.Emulator
{
    public class SensorEmulatorListItemModel
    {
        public double? Latitude { get; set; }

        public double? Longitude { get; set; }

        public bool IsOn { get; set; }

        public string ApiKey { get; set; }

        public string Guid { get; set; }

        public string Type { get; set; }
    }
}

src/Web/Areas/Admin/Models/Default/Emulator/SensorEmulatorListItemViewModel.cs
namespace Web.Areas.Admin.Models.Default.Emulator
{
    public class SensorEmulatorListItemViewModel
    {
        public double? Latitude { get; set; }

        public double? Longitude { get; set; }

        public bool IsOn { get; set; }

        public string ApiKey { get; set; }

        public string Guid { get; set; }

        public string Type { get; set; }
    }
}

src/Web/Areas/Admin/Controllers/API/EmulatorController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web.Application.Emulation.Commands;
using Web.Application.Emulation.Exceptions;
using Web.Areas.Admin.Models.API.Emulator;
using Web.Emulation;

namespace Web.Areas.Admin.Controllers.API
{
    [Area("Admin")]
    [Authorize]
    //TODO: check area based api routes
    [Route("api/{area}/{controller}")]
    public class EmulatorController : Controller
    {
        private readonly Emulator _emulator;
        private readonly IMediator _mediator;

        private static readonly IMapper _mapper = new Mapper(new MapperConfiguration(x =>
        {
            x.CreateMap<SensorEmulator, SensorEmulatorListItemModel>()
                .ForMember(f => f.Latitude, m => m.MapFrom((s, d) => s.Latitude))
                .ForMember(f => f.Longitude, m => m.MapFrom((s, d) => s.Longitude))
                .ForMember(f => f.Guid, m => m.MapFrom(s => s.GetGuid()))
                .ForMember(f => f.IsOn, m => m.MapFrom(s => s.IsPowerOn))
                .ForMember(f => f.ApiKey, m => m.MapFrom(s => s.ApiKey))
                .ForMember(f => f.Type, m => m.MapFrom(s => s.SensorType.Name))
                ;
        }));

        public EmulatorController(Emulator emulator, IMediator mediator)
        {
            _emulator = emulator;
            _mediator = mediator;
        }

        [HttpGet]
        public ActionResult Index()
        {
            List<SensorEmulator> emulators = new List<SensorEmulator>();
            if (_emulator.IsEmulationEnabled)
            {
                emulators = _emulator.Devices;
            }

            return Ok(_mapper.Map<List<SensorEmulator>, List<SensorEmulatorListItemModel>>(emulators));
        }


        [HttpPost]
        public async Task<IActionResult> StartEmulation()
        {
            try
            {
                await _mediator.Send(new BeginEmulationCommand());
            }
            catch (EmulationIsNotAvailableException ex)
            {
                return Forbid(ex.Message);
            }

            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> StopEmulation()
        {
            try
            {
                await _mediator.Send(new StopEmulationCommand());
            }
            catch (EmulationIsNotAvailableException ex)
            {
                return Forbid(ex.Message);
            }
            
            return Ok();
        }

        [HttpPost]
        public ActionResult PowerOn(string guid)
        {
            try
            {
                _mediator.Send(new DevicePowerOnCommand(guid));
            }
            catch (EmulationIsNotAvailableException ex)
            {
                return Forbid(ex.Message);
            }
            catch (EmulationDeviceNotFoundException ex)
            {
                return NotFound(ex.Message);
            }
            
            return Ok("Emulator device has been successfully started");
        }

        [HttpPost]
        public ActionResult PowerOff(string guid)
        {
            try
            {
                _mediator.Send(new DevicePowerOffCommand(guid));
            }
            catch (EmulationIsNotAvailableException ex)
            {
                return Forbid(ex.Message);
            }
            catch (EmulationDeviceNotFoundException ex)
            {
                return NotFound(ex.Message);
            }
            
            return Ok("Emulator device has been successfully stopped");
        }
    }
}

src/Web/Areas/Admin/Controllers/Default/EmulatorController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web.Areas.Admin.Application.Emulation.Commands;
using Web.Areas.Admin.Application.Emulation.Exceptions;
using Web.Areas.Admin.Application.Emulation.Queries;
using Web.Areas.Admin.Application.Emulation.Queries.DTO;
using Web.Areas.Admin.Extensions;
using Web.Areas.Admin.Infrastructure.Auth;
using Web.Areas.Admin.Models.Default.Emulator;

namespace Web.Areas.Admin.Controllers.Default
{
    [Area(AdminArea.Name)]
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Policy = AuthPolicies.Admin)]
    public class EmulatorController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;
        private readonly IEmulationQueries _emulationQueries;

        public EmulatorController(IMediator mediator, IMapper mapper, IEmulationQueries emulationQueries)
        {
            _mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _emulationQueries = emulationQueries ?? throw new ArgumentNullException(nameof(emulationQueries));
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var devices = await _emulationQueries.GetEmulatorDevicesAsync();
            return View(_mapper.Map<List<EmulatorDeviceDTO>, List<SensorEmulatorListItemViewModel>>(devices));
        }


        [HttpPost]
        public async Task<IActionResult> StartEmulation()
        {
            try
            {
                await _mediator.Send(new BeginEmulationCommand());
            }
            catch (EmulationIsNotAvailableException ex)
            {
                return this.StatusCodeView(HttpStatusCode.Forbidden, ex.Message);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> StopEmulation()
        {
            try
            {
                await _mediator.Send(new StopEmulationCommand());
            }
            catch (EmulationIsNotAvailableException ex)
            {
                return this.StatusCodeView(HttpStatusCode.Forbidden, ex.Message);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult PowerOn(string guid)
        {
            try
            {
                _mediator.Send(new DevicePowerOnCommand(guid));
            }
            catch (EmulationIsNotAvailableException ex)
            {
                return this.StatusCodeView(HttpStatusCode.Forbidden, ex.Message);
            }
            catch (EmulationDeviceNotFoundException ex)
            {
                return this.StatusCodeView(HttpStatusCode.NotFound, ex.Message);
            }

            return this.StatusCodeView(HttpStatusCode.OK, "Emulator device has been successfully started");
        }

        [HttpPost]
        public ActionResult PowerOff(string guid)
        {
            try
            {
                _mediator.Send(new DevicePowerOffCommand(guid));
            }
            catch (EmulationIsNotAvailableException ex)
            {
                return this.StatusCodeView(HttpStatusCode.Forbidden, ex.Message);
            }
            catch (EmulationDeviceNotFoundException ex)
            {
                return this.StatusCodeView(HttpStatusCode.NotFound, ex.Message);
            }

            return this.StatusCodeView(HttpStatusCode.OK, "Emulator device has been successfully stopped");
        }
    }
}

src/Web/Areas/Admin/Views/Emulator/Index.cshtml
@using Web.Areas.Admin.Emulation
@inject EmulationAppSettings EmulationAppSettings
@inject Emulator Emulator
@model List<Web.Areas.Admin.Models.Default.Emulator.SensorEmulatorListItemViewModel>
@{
    ViewBag.Title = "Датчики-эмуляторы";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.Page = "page-emulator-sensors";
}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class=" text-primary">
                            <tr>
                                <th>
                                    Локация
                                </th>
                                <th>
                                    Ключ API
                                </th>
                                <th>
                                    Тип
                                </th>
                                <th>
                                    Состояние
                                </th>
                                <th>
                                    Действия
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var sensor in Model)
                            {
                                <tr>
                                    <td>
                                        Lat: @sensor.Latitude,
                                        <br />
                                        Long: @sensor.Longitude
                                    </td>
                                    <td>
                                        @sensor.ApiKey
                                    </td>
                                    <td>
                                        @sensor.Type
                                    </td>
                                    <td>
                                        @(sensor.IsOn ? "Включен" : "Отключен")
                                    </td>
                                    <td>
                                        <a class="dropdown-toggle" href="javascript:void(0);" id="edit_button_@sensor.Guid" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <p>
                                                <span class="d-lg-none d-md-block">Дейсвтия</span>
                                            </p>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right sensor-actions" aria-labelledby="edit_button_@sensor.Guid">

                                            @using (Html.BeginForm($"{(!sensor.IsOn ? "PowerOn" : "PowerOff")}", "Emulator", new { area = "Admin", ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, null, new { @class = "form-horizontal", role = "form" }))
                                            {
                                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                                @Html.Hidden(nameof(sensor.Guid), sensor.Guid)
                                                <button class="dropdown-item">@(sensor.IsOn ? "Выключить" : "Включить")</button>
                                            }
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            @if (EmulationAppSettings.Enabled)
            {
                <div class="card-footer">
                    @using (Html.BeginForm($"{(Emulator.IsEmulationStarted ? "Stop" : "Start")}Emulation", "Emulator", new { area = "Admin", ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, null, new { @class = "form-horizontal", role = "form" }))
                    {
                        <button class="btn btn-default">@((Emulator.IsEmulationStarted ? "Выключить" : "Включить")) эмуляцию</button>
                    }
                </div>
            }
        </div>

    </div>
</div>